#! /bin/bash
# c.sh
yum -y install gcc;
sudo yum install zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel libffi-devel;
yum -y install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel libffi-devel;
wget https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tgz;
tar -zxvf Python-3.8.3.tgz;
mkdir /usr/local/python3;
cd Python-3.8.3;
./configure --prefix=/usr/local/python3;
make && make install;
ln -sf /usr/local/python3/bin/python3.8 /usr/bin/python3;
ln -sf /usr/local/python3/bin/pip3.8 /usr/bin/pip3;
"python3安装成功...";
python3 -V
